name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Installing packages
        run: pnpm i
  
      - name: Build App
        run: pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.0

